language: php
php:
  - 5.5
  - 5.6

sudo: false

before_script:
  - composer self-update
  - composer install
  - cp test/TestAsset/config.dist.php  test/TestAsset/config.php

script:
  - phpunit --coverage-text -c test/

after_script:
  - php vendor/bin/coveralls
