language: php
php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install
  - cp test/BitWeb/IdServicesTest/TestAsset/config.dist.php  test/BitWeb/IdServicesTest/TestAsset/config.php

script:
  - phpunit --coverage-text -c test/

after_script:
  - php vendor/bin/coveralls
